schema_version = "1.0.0"

id = "qr_code_maker"
name = "QR Code Maker"
tagline = "Basic QR Code Maker"
type = "add-on"
tags = ["User Interface"]
version = "0.0.1"
blender_version_min = "4.2.0"
website = "https://github.com/inkihong9/qr-code-with-blender"
maintainer = "Inki Hong <ihong3589@gmail.com>"
license = [
    "SPDX:GPL-3.0-or-later"
]
copyright = [
    "Inki Hong <ihong3589@gmail.com>"
]