name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Create libs directory
        run: mkdir -p libs

      - name: Install requests into libs folder
        run: |
          pip install qrcode --target libs

      # OPTIONAL: verify installation
      - name: Verify installed packages
        run: ls -la libs

      - name: Build Blender Addon
        uses: BlenderKit/blender-addon-build@v0.1
        with:
          name: 'QR Code Maker'
          name-suffix: 'commit-hash'
          build-command: 'make build'
          build-location: './build'
          do-checkout: 'true'
          exclude-files: '.git;.github;.gitignore'
